server:
  port: 8080

spring:

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        -  id: wishlist-service
           uri: http://ec2-3-142-80-0.us-east-2.compute.amazonaws.com:8082/
           predicates:
             - Path=/api/v1/wishlist/**
        -  id: auth-service
           uri: http://localhost:8085/
           predicates:
             - Path=/api/v1/auth/**
        - id: movie-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/movie/**
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1.0/user/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
